### ISSUE TITLE
onItemAtEndLoaded not always called

### ISSUE THREAD

**Issue by AhmedMourad0** [android/architecture-components-samples#307]
I'm using the PagingNetworkExample (room + network) where onItemAtEndLoaded is not called when i fast scroll down the list and to make it load more data from the network i have to scroll up a little and scroll back down.

This is my list:

```
        val config = PagedList.Config.Builder()
                .setPageSize(20)
                .setInitialLoadSizeHint(20)
//                .setPrefetchDistance(10)
                .setEnablePlaceholders(false)
                .build()

        runBlocking {

            moviesList = LivePagedListBuilder(
                    CinemaDatabase.getInstance(application)
                            .popularMoviesDao()
                            .getMoviesDataSource(), config)
                    .setBackgroundThreadExecutor(BackgroundThreadExecutor())
                    .setBoundaryCallback(PopularMoviesBoundaryCallback(application))
                    .build()
        }
```

The Room part:

```
     @Query(...)
    fun getMoviesDataSource(): DataSource.Factory<Int, MoviesEntity>
```

The BoundaryCallback:

```
class PopularMoviesBoundaryCallback(val context: Context) : PagedList.BoundaryCallback<MoviesEntity>() {

    override fun onZeroItemsLoaded() = SyncUtils.initialize(context)

    override fun onItemAtEndLoaded(itemAtEnd: MoviesEntity) {

        val prefs = defaultPrefs(context)

        fetchPopularMoviesData(context = context, page = prefs[KEY_PAGE_POPULAR, 1] + 1)

        prefs[KEY_PAGE_POPULAR] = prefs[KEY_PAGE_POPULAR, 1] + 1
    }
}
```

**Comment by 80998062** [comment]
Same issue here, any solution?

**Comment by Ekalips** [comment]
I have same issue. My BoundaryCallback works only one time (when no data in local storage and  `onZeroItemsLoaded` called). In my project I copied code from example, you can find it [here](https://github.com/Ekalips/CashCrowd/blob/master/app/src/main/java/com/ekalips/cahscrowd/data/event/paginate/EventsBoundaryCallback.kt) (BoundaryCallback part) or my full project [here](https://github.com/Ekalips/CashCrowd)

**Comment by msayan** [comment]
Same issue here, any solution?

**Comment by tjmille2** [comment]
@msayan Did changing placeholders help you? I think this bug is related to the paging library, as the link you provided claims to have been fixed on Jan 18th, 2018, but we are experiencing this bug with the latest provided code sample, still.

**Comment by msayan** [comment]
@tjmille2 yes it fixes the issue.

**Comment by yesiyan01** [comment]
Any update on this issue? Still experiencing the same behaviour.

**Comment by ChrisCraik** [comment]
Are you able to reproduce this in 1.0.0-beta1?

There was a fix in alpha7 for BoundaryCallback.onItemAtEndLoaded when placeholders are not disabled, see:

https://developer.android.com/topic/libraries/architecture/release-notes.html#march_21_2018

**Comment by mtangoo** [comment]
any fix on this?

**Comment by mtangoo** [comment]
@ChrisCraik enabling/disabling placeholder does not work. I have one item only and page size is 8
Items in server are added and I expected trying to scroll that one item will call the method but didn't

**Comment by guitoun3** [comment]
I had the same issue where onItemAtFrontLoaded nor onItemAtEndLoaded was executed. I found out that I was using a wrong adapter type. I needed to use a PagedListAdapter (I was using a ListAdapter)🤦

**Comment by percula** [comment]
I created an issue on the Google Issue Tracker, please star it if you are still encountering this bug: https://issuetracker.google.com/issues/135966530

**Comment by DanteAndroid** [comment]
Same issue here.

**Comment by HashemDeveloper** [comment]
> Same issue here. onItemAtEndLoaded is only called when the first load happens (with onZeroItemsLoaded called)
You should make sure that the pageSize you assign when configuring the pageList, is greater than the size of list you fetch from the server. For example, if you are fetching 30 items from the server, setPageSize to 40(you can set 31 and this will work too!). This will trigger onZeroItemsLoaded each time you start the app. Let me know if it helped solving your problem.

**Comment by HashemDeveloper** [comment]
Make sure that the pageSize you assign when configuring the pageList, is greater than the size of list you fetch from the server. For example, if you are fetching 30 items from the server, setPageSize to 40(you can set 31 and this will work too!). This will trigger onZeroItemsLoaded each time you start the app. Let me know if it helped solving your problem.

**Comment by dlam** [comment]
Thanks for all the replies here - appreciate filing against our issuetracker as well. As noted in the bug, this v2 api has been superseded by `RemoteMediator` in v3, so I don't really anticipate fixes as there is still a lot to do and realistically this won't make it before v3 goes stable :(
